name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1 # Change this to the location of your S3 Bucket

    # Change ./_site/ to the location of your website in your repository,
    # with Jekyll _site/ is the default location of the built files
    - name: Deploy to S3 bucket
      run: aws s3 sync ./_site/ ${{ secrets.S3_BUCKET }} --delete
